server:
  port: ${PORT:8802}
  forward-headers-strategy: framework

asana:
  client-secret: ${ASANA_CLIENT_SECRET:}
  api-base-url: https://app.asana.com/api/1.0
  personal-access-token: ${ASANA_PAT:}

service-assets:
  base-url: ${SERVICE_ASSETS_URL:http://baker-service-assets}

file-transfer:
  max-concurrent: 5
  timeout-minutes: 10
