server:
  port: ${PORT:8802}
  forward-headers-strategy: framework

asana:
  client-secret: ${ASANA_CLIENT_SECRET:cc812f9cf41ccb989ccdde9679794d24}
  api-base-url: https://app.asana.com/api/1.0
  pat: ${ASANA_PAT:}

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:https://login.us-1.golytho.us/auth}
  realm: ${KEYCLOAK_REALM:qaorange}
  client-id: ${KEYCLOAK_CLIENT_ID:asana-integration}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:}
  redirect-uri: ${KEYCLOAK_REDIRECT_URI:}

identity-mapping:
  require-workspace-tenant-mapping: ${REQUIRE_WORKSPACE_TENANT_MAPPING:false}
  require-dam-user-mapping: ${REQUIRE_DAM_USER_MAPPING:false}
  workspace-tenant-map: {}
  asana-user-dam-user-map: {}

service-assets:
  base-url: ${SERVICE_ASSETS_URL:http://baker-service-assets}

file-transfer:
  max-concurrent: 5
  timeout-minutes: 10
