CREATE TABLE IF NOT EXISTS asana_connection (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asana_workspace_gid VARCHAR(64) NOT NULL,
  asana_user_gid      VARCHAR(64) NOT NULL,
  tenant_id           VARCHAR(64) NOT NULL,
  keycloak_realm      VARCHAR(128) NOT NULL,
  keycloak_user_id    VARCHAR(128) NOT NULL,
  token_type          VARCHAR(32) NOT NULL,
  refresh_token_enc   TEXT,
  offline_token_enc   TEXT,
  scope               TEXT,
  status              VARCHAR(32) NOT NULL,
  last_used_at        TIMESTAMP NULL,
  created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_asana_connection_workspace_user UNIQUE (asana_workspace_gid, asana_user_gid)
);

CREATE TABLE IF NOT EXISTS asana_link_state (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_nonce         VARCHAR(128) NOT NULL UNIQUE,
  asana_workspace_gid VARCHAR(64) NOT NULL,
  asana_user_gid      VARCHAR(64) NOT NULL,
  tenant_id           VARCHAR(64) NOT NULL,
  expires_at          TIMESTAMP NOT NULL,
  created_at          TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_asana_connection_status ON asana_connection(status);
CREATE INDEX IF NOT EXISTS idx_asana_connection_workspace_user ON asana_connection(asana_workspace_gid, asana_user_gid);
CREATE INDEX IF NOT EXISTS idx_asana_link_state_expires ON asana_link_state(expires_at);
